# Generated by Django 4.0.3 on 2022-03-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_rename_conmment_reviews_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='creat_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
