# Generated by Django 4.0.3 on 2022-03-03 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='video_file',
            new_name='video_url',
        ),
    ]
